tuning: 
  - interval: [100/1200, 7]
  - interval: [200/1200, 6]
  - interval: [300/1200, 5]
  - interval: [400/1200, 3]
  - interval: [500/1200, 2]
  - interval: [600/1200, 5]
  - interval: [700/1200, 1]
  - interval: [800/1200, 5]
  - interval: [900/1200, 4]
  - interval: [1000/1200, 5]
  - interval: [1100/1200, 7]
  - interval: [1200/1200, 0]
scales:
  - name: Heptatonic
    scales:
      - name: Heptatonic First
        notes: [0, 2, 4, 5, 7, 9, 11]  # 2-2-1-2-2-2-1
      - name: Heptatonic Second
        notes: [0, 2, 3, 5, 7, 9, 11]  # 2-1-2-2-2-2-1
      - name: Harmonic Minor
        notes: [0, 2, 4, 5, 7, 8, 11]  # 2-2-1-2-1-3-1
      - name: Harmonic Major
        notes: [0, 2, 3, 5, 7, 8, 11]  # 2-1-2-2-1-3-1
    chords:
      - name: Seventh
        notes: [0, 2, 4, 6]