tuning: [0, 100/1200, 200/1200, 300/1200, 400/1200, 500/1200, 600/1200, 700/1200, 800/1200, 900/1200, 1000/1200, 1100/1200, 1200/1200]
scales:
  - name: Ionian (Major)
    notes: [0, 2, 4, 5, 7, 9, 11]
  - name: Dorian
    notes: [0, 2, 3, 5, 7, 9, 10]
  - name: Phrygian
    notes: [0, 1, 3, 5, 7, 8, 10]
  - name: Lydian
    notes: [0, 2, 4, 5, 7, 9, 11]
  - name: Mixolydian
    notes: [0, 2, 4, 5, 7, 9, 10]
  - name: Aeolian (Minor)
    notes: [0, 2, 3, 5, 7, 8, 10]
  - name: Locrian
    notes: [0, 1, 3, 5, 6, 8, 10]
chords:
  - name: Diminished Seventh
    notes: [0, 3, 6, 9]
  - name: Half Diminished Seventh
    notes: [0, 3, 6, 10]
  - name: Minor Seventh
    notes: [0, 3, 7, 10]
  - name: Minor Major
    notes: [0, 3, 7, 11]
  - name: Major Seventh
    notes: [0, 4, 7, 11]
  - name: Dominant Seventh
    notes: [0, 4, 7, 10]
  - name: Augmented Dominant Seventh
    notes: [0, 4, 8, 10]
  - name: Augmented Major Seventh
    notes: [0, 4, 8, 11]
