tuning: [0, 100/1200, 200/1200, 300/1200, 400/1200, 500/1200, 600/1200, 700/1200, 800/1200, 900/1200, 1000/1200, 1100/1200, 1200/1200]
modes:
  - name: Major (Ionian)
    notes: [0, 2, 4, 5, 7, 9, 11]
  - name: Dorian
    notes: [0, 2, 3, 5, 7, 9, 10]
  - name: Phrygian
    notes: [0, 1, 3, 5, 7, 8, 10]
  - name: Lydian
    notes: [0, 2, 4, 5, 7, 9, 11]
  - name: Mixolydian
    notes: [0, 2, 4, 5, 7, 9, 10]
  - name: Natural Minor (Aeolian)
    notes: [0, 2, 3, 5, 7, 8, 10]
  - name: Harmonic Minor
    notes: [0, 2, 3, 5, 7, 8, 11]
  - name: Melodic Minor
    notes: [0, 2, 3, 5, 7, 9, 11]
  - name: Locrian
    notes: [0, 1, 3, 5, 6, 8, 10]
chords:
  - name: Seventh
    notes: [0, 2, 4, 6]

