tuning:
  name: 12EDO
  eq: [12, 1] # 12 equal divisions of 1 octave
groups:
  - group: Chromatic
    scales:
      - name: Chromatic
        notes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    chords:
      - name: Power
        notes: [0, 7]
      - name: Major
        notes: [0, 4, 7]
      - name: Minor
        notes: [0, 3, 7]
      - name: Diminished
        notes: [0, 3, 6]
      - name: Augmented
        notes: [0, 4, 8]
  - group: Heptatonic
    scales:
      - name: Primary # Major / Natural Minor
        notes: [0, 2, 4, 5, 7, 9, 11]  # 2-2-1-2-2-2-1
      - name: Secondary
        notes: [0, 2, 3, 5, 7, 9, 11]  # 2-1-2-2-2-2-1
      - name: Tertiary
        notes: [0, 1, 2, 4, 6, 8, 10]  # 1-1-2-2-2-2-2
      - name: Harmonic Minor
        notes: [0, 2, 4, 5, 7, 8, 11]  # 2-2-1-2-1-3-1
      - name: Harmonic Major
        notes: [0, 2, 3, 5, 7, 8, 11]  # 2-1-2-2-1-3-1
      - name: Double harmonic
        notes: [0, 1, 4, 5, 7, 8, 11]
    chords:
      - name: Tertian
        notes: [0, 2, 4, 6]
      - name: Quartal
        notes: [0, 3, 6, 9]
      - name: Quintal
        notes: [0, 4, 8, 12]