tuning:
  name: 13EDT
  eq: [13, 1.585] # 13 equal divisions of 1 tritave (log2(3))
groups:
  - group: Chromatic
    scales:
      - name: Chromatic
        notes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    chords:
      - name: Major
        notes: [0, 4, 7]
      - name: Minor
        notes: [0, 3, 7]
      - name: Diminished
        notes: [0, 3, 6]
      - name: Augmented
        notes: [0, 4, 8]